pull_request_rules:
- name: automatic merge of dependabot
  conditions:
    - base=main
    - author~=^dependabot(|-preview)\[bot\]$
    - check-success=build
  actions:
    merge:
      method: merge
