pull_request_rules:
- name: automatic merge of dependabot
  conditions:
    - base=main
    - author~=^dependabot(|-preview)\[bot\]$
    - check-success~=build \(3\.\d+\)$
  actions:
    merge:
      method: merge
